# Generated by Django 4.2 on 2023-05-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
