# Generated by Django 4.2 on 2023-05-19 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_user_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
